# -*- coding: utf-8 -*-
"""MineSweeper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jzby29ZtnAf9dR2N_2ooZWRuPpnIecQE
"""

import numpy as np
import random
import copy
import Agent
import Environment
import strategies

def iteration(agent,x,y):
    if(agent.agentBoard[x][y] != -2):
        print("SHOULDN'T COME HERE ERROR!!");
    # agent.agentBoard[x][y] = agent.env.reveal(x,y)
    agent.updateKnowledge(x,y,agent.env.reveal(x,y),True)
    agent.printMinesweeper()

def playMinesweeper(env, getNextCell):
    agent = Agent.Agent(env,0)
    blasts = 0
    noOfIter = 0
    agent.printMinesweeper();
    while(agent.getUnknownCount() > 0):
        noOfIter += 1
        (x,y) = getNextCell(agent)
        print("Revealed: "+str(x)+" "+str(y))
        result = agent.env.reveal(x,y)
        if(result == -1):
            print("Bomb blast")
            blasts += 1
        # agent.agentBoard[x][y] = result
        agent.updateKnowledge(x,y,result,True)
        # agent.printMinesweeper()
    agent.printMinesweeper()
    return blasts

def playMinesweeperAI(env, getNextCell):
    agent = Agent.Agent(env,0)
    blasts = 0
    noOfIter = 0
    agent.printMinesweeper();
    (x,y) = strategies.getFirstRandomNextCell(agent)
    iteration(agent,x,y)
    while(agent.getUnknownCount() > 0):
        noOfIter += 1
        (res,x,y) = getNextCell(agent)
        resultString = "Revealed: "+str(x)+" "+str(y)+" "
        if(res == -2 or res == -3):
            result = agent.env.reveal(x,y)
            if(result == -1):
                resultString += "Bomb blast"
                blasts += 1
            elif(res == -3):
                resultString += "Found safe cell"
        else:
            resultString += "Found Bomb"
            result = -1
        # agent.agentBoard[x][y] = result
        print(resultString)
        agent.updateKnowledge(x,y,result,True)
        agent.printMinesweeper()
    agent.printMinesweeper()
    return blasts

